---


image: debian:testing-20210208


stages:
  - test


before_script:
  - apt-get update
  - apt-get install -y make racket sqlite3


test:
  stage: test
  script:
    - raco pkg install --name counter
    - raco test --collection counter
